port: 3000
endpoints:
    login: "/auth/api/v1/login"
    verify: "/auth/api/v1/verify"
users:
    login1: 9Hht8FGjoIkdq4Fvy48P+Bii+2xwX/gy8LL66hxvr+M=
    login2: QfDHBPAvonRXeHQ0/VEPzLsDK0+9xbNmYwd/rsy6AJk=
