port: 3000
endpoints:
    login: "/auth/api/v1/login"
    verify: "/auth/api/v1/verify"
users:
    login1: el8UUR9W4NuNjS9U9yaIQDAEyMu5on9hzvz5Fi9NkeM=
    login2: G8mgqmAtF1hKi/g7K3OE2BKfgwSXALXarD8kI6cL0y8=
